version: '2.1'
services:
  certs:
    build: tls
    volumes:
      - ./certs:/certs

  tinkerbell:
    build: .
    environment: 
      FACILITY: ${FACILITY:-lab1}
      PACKET_ENV: ${PACKET_ENV:-testing}
      PACKET_VERSION: ${PACKET_VERSION:-5efab5ef3a42cb88f2d54f4ed3201c2dd6797b7d}
      ROLLBAR_TOKEN: ${ROLLBAR_TOKEN:-9b78d0ad01d1467aa92c49c3a349b79d}
      ROLLBAR_DISABLE: ${ROLLBAR_DISABLE:-0}
      MAX_WORKFLOW_DATA_VERSIONS: 5
      PGDATABASE: tinkerbell
      PGHOST: db
      PGPASSWORD: tinkerbell
      PGPORT: 5432
      PGSSLMODE: disable
      PGUSER: tinkerbell
    depends_on:
      - "db"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- 127.0.0.1:42114/cert"]
      interval: 5s
      timeout: 2s
      retries: 30
    volumes:
      - ./certs:/certs/${FACILITY}
    logging:
      driver: fluentd
      options:
        tag: tinkerbell-server
    ports:
      - 42113:42113/tcp
      - 42114:42114/tcp

  db:
    build:
      context: deploy
    environment:
      POSTGRES_DB: tinkerbell
      POSTGRES_PASSWORD: tinkerbell
      POSTGRES_USER: tinkerbell
    ports:
      - 5432:5432
    #depends_on:
    #- "fluentbit"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tinkerbell"]
      interval: 1s
      timeout: 1s
      retries: 30

  registry:
    build:
      context: registry
      args:
        REGISTRY_USERNAME: $ROVER_REGISTRY_USER
        REGISTRY_PASSWORD: $ROVER_REGISTRY_PASS
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/server.pem
      REGISTRY_HTTP_TLS_KEY: /certs/server-key.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes:
      - ./certs:/certs
    network_mode: host

  boots:
    image: quay.io/packet/boots:workflow
    network_mode: host
    command: -dhcp-addr 0.0.0.0:67 -tftp-addr $HOST_IP:69 -http-addr $HOST_IP:80 -log-level DEBUG
    environment:
      API_AUTH_TOKEN: ${PACKET_API_AUTH_TOKEN:-PcyR6MvHb7wMmyYf9p8dJ2Dvnb9HxX8E}
      API_CONSUMER_TOKEN: ${PACKET_CONSUMER_TOKEN:-djR2TAvbnkY92i8Ea2KFMZW6MusW1fk7qzeCUHgtnQRSsXnqxoCr6V2vhSxpqASf}
      FACILITY_CODE: ${FACILITY:-lab1}
      PACKET_ENV: ${PACKET_ENV:-testing}
      PACKET_VERSION: ${PACKET_VERSION:-5efab5ef3a42cb88f2d54f4ed3201c2dd6797b7d}
      ROLLBAR_TOKEN: ${ROLLBAR_TOKEN:-9b78d0ad01d1467aa92c49c3a349b79d}
      ROLLBAR_DISABLE: ${ROLLBAR_DISABLE:-0}
      MIRROR_HOST: ${MIRROR_HOST:-127.0.0.1}
      CACHER_GRPC_AUTHORITY: 127.0.0.1:42111
      CACHER_CERT_URL: http://127.0.0.1:42112/cert
      DNS_SERVERS: "147.75.207.207,147.75.207.208"
      PUBLIC_IP: $HOST_IP
      BOOTP_BIND: $HOST_IP:67
      HTTP_BIND: $HOST_IP:80
      SYSLOG_BIND: $HOST_IP:514
      TFTP_BIND: $HOST_IP:69
      DOCKER_REGISTRY: $HOST_IP
      REGISTRY_USERNAME: $ROVER_REGISTRY_USER
      REGISTRY_PASSWORD: $ROVER_REGISTRY_PASS
      ROVER_GRPC_AUTHORITY: $HOST_IP:42113
      ROVER_CERT_URL: http://$HOST_IP:42114/cert
      ELASTIC_SEARCH_URL: $HOST_IP:9200
    depends_on:
      - server
    ports:
      - $HOST_IP:80:80/tcp
      - 67:67/udp
      - 69:69/udp
    
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - $NGINX_IP:80:80/tcp
    volumes:
      - /packet/nginx/:/var/www/html/

  elasticsearch:
    image: elasticsearch:7.3.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  kibana:
    image: kibana:7.3.0
    depends_on:
      - elasticsearch
    restart: always
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601

  fluentbit:
    image: fluent/fluent-bit:1.3
    ports:
      - 24224:24224
      - 24224:24224/udp
    depends_on:
      - kibana
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  cserver:
    image: quay.io/packet/cacher:workflow
    environment:
      FACILITY: ${FACILITY:-lab1}
      PACKET_API_AUTH_TOKEN: ${PACKET_API_AUTH_TOKEN}
      PACKET_API_URL: ${PACKET_API_URL}
      PACKET_CONSUMER_TOKEN: ${PACKET_CONSUMER_TOKEN-djR2TAvbnkY92i8Ea2KFMZW6MusW1fk7qzeCUHgtnQRSsXnqxoCr6V2vhSxpqASf}
      PACKET_ENV: testing
      PACKET_VERSION: 5efab5ef3a42cb88f2d54f4ed3201c2dd6797b7d
      PGDATABASE: rover
      PGHOST: db
      PGPASSWORD: rover
      PGPORT: 5432
      PGSSLMODE: disable
      PGUSER: rover
      ROLLBAR_TOKEN: 9b78d0ad01d1467aa92c49c3a349b79d
    volumes:
      - ./certs:/certs/${FACILITY}
    ports:
      - 42111:42111/tcp
      - 42112:42112/tcp

  hegel:
    image: quay.io/packet/hegel:workflow
    network_mode: host
    environment:
      ROLLBAR_TOKEN: 9b78d0ad01d1467aa92c49c3a349b79d
      ROLLBAR_DISABLE: 1
      PACKET_ENV: testing
      PACKET_VERSION: 5efab5ef3a42cb88f2d54f4ed3201c2dd6797b7d
      GRPC_PORT: 42115
      HEGEL_FACILITY: ${FACILITY:-lab1}
      HEGEL_USE_TLS: 0
      CACHER_CERT_URL: http://127.0.0.1:42112/cert
      CACHER_GRPC_AUTHORITY: 127.0.0.1:42111
