apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: server-role
rules:
  - apiGroups:
      - tinkerbell.org
    resources:
      - hardware
      - hardware/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tinkerbell.org
    resources:
      - templates
      - templates/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tinkerbell.org
    resources:
      - workflows
      - workflows/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
