# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - bases/tinkerbell.org_hardware.yaml
  - bases/tinkerbell.org_templates.yaml
  - bases/tinkerbell.org_workflows.yaml
  - bases/tinkerbell.org_workflowdata.yaml
#+kubebuilder:scaffold:crdkustomizeresource

# Labels to add to all resources and selectors.
commonLabels:
  clusterctl.cluster.x-k8s.io: ""
  clusterctl.cluster.x-k8s.io/move: ""

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
  - kustomizeconfig.yaml
