apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.4
  name: workflows.tinkerbell.org
spec:
  group: tinkerbell.org
  names:
    categories:
      - tinkerbell
    kind: Workflow
    listKind: WorkflowList
    plural: workflows
    shortNames:
      - wf
    singular: workflow
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.templateRef
          name: Template
          type: string
        - jsonPath: .status.state
          name: State
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Workflow is the Schema for the Workflows API.
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: WorkflowSpec defines the desired state of Workflow.
              properties:
                hardwareMap:
                  additionalProperties:
                    type: string
                  description: A mapping of template devices to hadware mac addresses
                  type: object
                hardwareRef:
                  description: Name of the Hardware associated with this workflow.
                  type: string
                templateRef:
                  description: Name of the Template associated with this workflow.
                  type: string
              type: object
            status:
              description: WorkflowStatus defines the observed state of Workflow.
              properties:
                globalTimeout:
                  description: GlobalTimeout represents the max execution time
                  format: int64
                  type: integer
                state:
                  description: State is the state of the workflow in Tinkerbell.
                  type: string
                tasks:
                  description: Tasks are the tasks to be completed
                  items:
                    description: Task represents a series of actions to be completed by a worker.
                    properties:
                      actions:
                        items:
                          description: Action represents a workflow action.
                          properties:
                            command:
                              items:
                                type: string
                              type: array
                            environment:
                              additionalProperties:
                                type: string
                              type: object
                            image:
                              type: string
                            message:
                              type: string
                            name:
                              type: string
                            pid:
                              type: string
                            seconds:
                              format: int64
                              type: integer
                            startedAt:
                              format: date-time
                              type: string
                            status:
                              type: string
                            timeout:
                              format: int64
                              type: integer
                            volumes:
                              items:
                                type: string
                              type: array
                          type: object
                        type: array
                      environment:
                        additionalProperties:
                          type: string
                        type: object
                      name:
                        type: string
                      volumes:
                        items:
                          type: string
                        type: array
                      worker:
                        type: string
                    required:
                      - actions
                      - name
                      - worker
                    type: object
                  type: array
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
    - additionalPrinterColumns:
        - description: State of the workflow such as Pending,Running etc
          jsonPath: .status.state
          name: State
          type: string
        - description: Hardware object that runs the workflow
          jsonPath: .spec.hardwareRef
          name: Hardware
          type: string
        - description: Template to run on the associated Hardware
          jsonPath: .spec.templateRef
          name: Template
          type: string
      name: v1alpha2
      schema:
        openAPIV3Schema:
          description: Workflow describes a set of actions to be run on a specific Hardware. Workflows execute once and should be considered ephemeral.
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              properties:
                hardwareRef:
                  description: HardwareRef is a reference to a Hardware resource this workflow will execute on. If no namespace is specified the Workflow's namespace is assumed.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                  x-kubernetes-map-type: atomic
                templateParams:
                  additionalProperties:
                    type: string
                  description: "TemplateParams are a list of key-value pairs that are injected into templates at render time. TemplateParams are exposed to templates using a top level .Params key. \n For example, TemplateParams = {\"foo\": \"bar\"}, the foo key can be accessed via .Params.foo."
                  type: object
                templateRef:
                  description: TemplateRef is a reference to a Template resource used to render workflow actions. If no namespace is specified the Workflow's namespace is assumed.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                  x-kubernetes-map-type: atomic
                timeout:
                  default: 0
                  description: TimeoutSeconds defines the time the workflow has to complete. The timer begins when the first action is requested. When set to 0, no timeout is applied.
                  format: int64
                  minimum: 0
                  type: integer
              type: object
            status:
              properties:
                actions:
                  description: Actions is a list of action states.
                  items:
                    description: ActionStatus describes status information about an action.
                    properties:
                      failureMessage:
                        description: FailureMessage is a free-form user friendly message describing why the Action entered the ActionStateFailed state. Typically, this is an elaboration on the Reason.
                        type: string
                      failureReason:
                        description: FailureReason is a short CamelCase word or phrase describing why the Action entered ActionStateFailed.
                        type: string
                      id:
                        description: ID uniquely identifies the action status.
                        type: string
                      lastTransitioned:
                        description: LastTransition is the observed time when State transitioned last.
                        format: date-time
                        type: string
                      rendered:
                        description: Rendered is the rendered action.
                        properties:
                          args:
                            description: Args are a set of arguments to be passed to the command executed by the container on launch.
                            items:
                              type: string
                            type: array
                          cmd:
                            description: Cmd defines the command to use when launching the image. It overrides the default command of the action. It must be a unix path to an executable program.
                            pattern: ^(/[^/ ]*)+/?$
                            type: string
                          env:
                            additionalProperties:
                              type: string
                            description: Env defines environment variables used when launching the container.
                            type: object
                          image:
                            description: Image is an OCI image.
                            type: string
                          name:
                            description: Name is a name for the action.
                            type: string
                          namespaces:
                            description: Namespace defines the Linux namespaces this container should execute in.
                            properties:
                              network:
                                description: Network defines the network namespace.
                                type: string
                              pid:
                                description: PID defines the PID namespace
                                type: integer
                            type: object
                          volumes:
                            description: Volumes defines the volumes to mount into the container.
                            items:
                              description: "Volume is a specification for mounting a volume in an action. Volumes take the form {SRC-VOLUME-NAME | SRC-HOST-DIR}:TGT-CONTAINER-DIR:OPTIONS. When specifying a VOLUME-NAME that does not exist it will be created for you. Examples: \n Read-only bind mount bound to /data \n /etc/data:/data:ro \n Writable volume name bound to /data \n shared_volume:/data \n See https://docs.docker.com/storage/volumes/ for additional details."
                              type: string
                            type: array
                        required:
                          - image
                          - name
                        type: object
                      startedAt:
                        description: StartedAt is the time the action was started as reported by the client. Nil indicates the Action has not started.
                        format: date-time
                        type: string
                      state:
                        description: State describes the current state of the action.
                        type: string
                    required:
                      - id
                    type: object
                  type: array
                conditions:
                  description: Conditions details a set of observations about the Workflow.
                  items:
                    description: Condition defines an observation on a resource that is generally attainable by inspecting other status fields.
                    properties:
                      lastTransitionTime:
                        description: LastTransition is the last time the condition transitioned from one status to another.
                        format: date-time
                        type: string
                      message:
                        description: Message is a human readable message indicating details about the last transition.
                        type: string
                      reason:
                        description: Reason is a short CamelCase description for the conditions last transition.
                        type: string
                      status:
                        description: Status of the condition.
                        type: string
                      type:
                        description: Type of condition.
                        type: string
                    required:
                      - lastTransitionTime
                      - status
                      - type
                    type: object
                  type: array
                lastTransitioned:
                  description: LastTransition is the observed time when State transitioned last.
                  format: date-time
                  type: string
                startedAt:
                  description: StartedAt is the time the first action was requested. Nil indicates the Workflow has not started.
                  format: date-time
                  type: string
                state:
                  description: State describes the current state of the workflow. For the workflow to enter the WorkflowStateSucceeded state all actions must be in ActionStateSucceeded. The Workflow will enter a WorkflowStateFailed if 1 or more Actions fails.
                  type: string
              required:
                - actions
                - conditions
              type: object
          type: object
      served: false
      storage: false
      subresources:
        status: {}
